language: python
cache: pip
dist: bionic
matrix:
    fast_finish: true
    include:

      - { python: "3.6", env: DJANGO=2.2 }
      - { python: "3.6", env: DJANGO=3.0 }
      - { python: "3.6", env: DJANGO=3.1 }
      - { python: "3.6", env: DJANGO=master }

      - { python: "3.7", env: DJANGO=2.2 }
      - { python: "3.7", env: DJANGO=3.0 }
      - { python: "3.7", env: DJANGO=3.1 }
      - { python: "3.7", env: DJANGO=master }

      - { python: "3.8", env: DJANGO=3.0 }
      - { python: "3.8", env: DJANGO=3.1 }
      - { python: "3.8", env: DJANGO=master }

      - { python: "3.9-dev", env: DJANGO=3.1 }
      - { python: "3.9-dev", env: DJANGO=master }

      - python: "3.8"
        env: TOXENV=base
        script:
          - python setup.py bdist_wheel
          - rm -r django_q_filter.egg-info
          - tox --installpkg ./dist/django_q_filter-*.whl
          - tox  # test sdist

    allow_failures:
      - env: DJANGO=master

install:
    - pip install tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
    email: false
